### ISSUE TITLE
issue with twitter setup

### ISSUE THREAD

**Issue by sridharsai84** [splunk/splunk-app-twitter#5]
HI,

ANY HELP ON THIS IS APPRECIATED.

when i installed twitter app and go to setup page.. i give keys after which it runs for long time and throws an xml error page as time out.

User 'admin' triggered the '_reload' action on app 'twitter2', and the following objects required a restart: restart_on_install

again i am reloading but it doesnt finish..any help..i set REST api as well...

**Comment by napomokoetle** [comment]
Hi,

I'm also experiencing the problem as per sridharsai84 above. Could you kindly help me resolve it please. I'm running Splunk 6.2 on Ubuntu 1410

Error reads: 
"ser 'admin' triggered the '_reload' action on app 'twitter2', and the following objects required a restart: restart_on_install"

I provided all the setup parameters is given my the OAuth Tool in dev.twitter.com :
Cosumer Key, Consumer secret, Access token & Access token secret
But I get message saying "Invalid Twitter credentials."

Thanks in advance for your help.

**Comment by davidfstr** [comment]
> "ser 'admin' triggered the '_reload' action on app 'twitter2', and the following objects required a restart: restart_on_install"

Restart Splunk.

**Comment by napomokoetle** [comment]
Hi David, I did restart Splunk several times now but the error persists and I can't got move beyond the configuration form. I even tried reinstalling the App but that didn't work either.

I'm suspicious the the proxy might have to do with the problem. I've configured Splunk to have access to the Internet though. For instance I'm able to install a Splunk APP from Splunkbase without any problem.

**Comment by davidfstr** [comment]
If the app cannot communicate with Twitter it will assume that it is because of bad credentials, so it is likely that the proxy may be at fault.

You could open a packet analyzer and see whether requests to twitter.com are being blocked.

**Comment by napomokoetle** [comment]
Hi David,

Thank you very much for your assistance. 

I have installed a different instance of Splunk on my laptop and added the Twitter App but I still get the same messages as above even when I'm on a network with no proxy!
So I guess there is something else happening to prevent the app from working as it should.

Also, the following message keeps coming through even though I've restarted Splunk many times. Could this be a bug?

===================+
User 'admin' triggered the '_reload' action on app 'twitter2', and the following objects required a restart: restart_on_install
2/5/2015, 11:12:13 AM
User 'admin' triggered the '_reload' action on app 'twitter2', and the following objects required a restart: restart_on_install
2/5/2015, 11:12:13 AM
User 'admin' triggered the '_reload' action on app 'twitter2', and the following objects required a restart: restart_on_install
2/5/2015, 11:12:13 AM
User 'admin' triggered the '_reload' action on app 'twitter2', and the following objects required a restart: restart_on_install
2/5/2015, 11:12:13 AM
User 'admin' triggered the '_reload' action on app 'twitter2', and the following objects required a restart: restart_on_instal
===================+
